### ISSUE TITLE
Dashboard repeatedly flashes error banner

### ISSUE THREAD

**Issue by dsummersl** [kubemq-io/kubemq-community#35]
When I run the following command:

    docker run -d -p 8080:8080 -p 50000:50000 -p 9090:9090 kubemq/kubemq-community:latest  

And then go to http://localhost:8080/dashboard

I see the dashboard, and I see a banner appear at the top every few seconds: "KubeMQ Server is Disconnected".

I was able to create a channel and send messages to the channel, so other things appear to work - but not the web interface :(

**Comment by dsummersl** [comment]
Also notice this in the Chrome browser console:


```
Uncaught SyntaxError: Unexpected end of JSON input
    at JSON.parse (<anonymous>)
    at onMessage (default.b5462131.js:1:2721)
    at g.onmessage (stream.cbe555aa.js:1:9502)
```

**Comment by kubemq** [comment]
the connection between the dashboard and server is done via web socket. we saw several cases that the docker engine / policy on the machine disconnecting the link.
